# Generated by Django 3.0.2 on 2020-01-30 19:46

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle', models.CharField(max_length=255, null=True)),
                ('rms', models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('avg_rms', models.FloatField()),
                ('mvc', models.FloatField()),
                ('historic_mvc', models.FloatField()),
            ],
        ),
    ]
