# Generated by Django 3.0.3 on 2020-07-20 19:55

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0004_auto_20200719_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='raw',
            field=models.CharField(default=[], max_length=50000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='wave',
            name='rms',
            field=models.CharField(max_length=5000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
