# Generated by Django 3.0.3 on 2020-07-20 20:03

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0005_auto_20200720_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='raw',
            field=models.CharField(default=[], max_length=500000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
