# Generated by Django 3.0.3 on 2020-07-28 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waves', '0007_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='type',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'other')], default=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
