# Generated by Django 3.0.3 on 2020-07-28 21:31

from django.db import migrations, models
import src.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0008_auto_20200728_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='photo',
            field=models.ImageField(storage=src.storage_backends.PrivateMediaStorage(), upload_to='patients'),
        ),
    ]
