# Generated by Django 3.0.3 on 2020-08-17 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waves', '0010_auto_20200729_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('video', models.FileField(storage=src.storage_backends.PrivateMediaStorage(), upload_to='diagnoses')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waves.Suite')),
            ],
        ),
    ]
